# Generated by Django 4.2.3 on 2023-07-09 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_rename_created_at_customer_db_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_db',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
