# Generated by Django 4.2.3 on 2023-07-09 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_alter_customer_db_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_db',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
