# Generated by Django 4.2.3 on 2023-07-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_alter_customer_db_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_db',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer_db',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
