# Generated by Django 4.2.3 on 2023-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_alter_customer_db_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_db',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
