# Generated by Django 4.2.3 on 2023-07-09 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_customer_db_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_db',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='customer_db',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
